services:
  nginx:
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - SSL_TYPE=none
    ports: []
    networks:
      - proxy
      - default

  enketo:
    environment:
      - SSL_TYPE=none
    networks:
      - proxy
      - default

networks:
  proxy:
    external: true